server:
  port: 8081
  servlet:
    context-path: /chat-service

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hyoukachatdemodb
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
